# Generated by Django 5.2.6 on 2025-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodoInformaticaProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='productos',
            field=models.ManyToManyField(to='appTodoInformaticaProyecto.producto'),
        ),
    ]
